# Generated by Django 5.0.7 on 2024-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_drf_app', '0002_rename_auth_status_user_drf_amaliyot_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_drf_amaliyot',
            name='email',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
